### ISSUE TITLE
Error in Pix2Pix

### ISSUE THREAD

**Issue by LukasMosser** [tdeboissiere/DeepLearningImplementations#12]
Line 177 using tensorflow I get this error message on running:
Input 'input_sizes' of 'Conv2DBackpropInput' Op has type float32 that does not match expected type of int32.

Possibly input tensor needs to be converted to float32 or int32?

**Comment by tdeboissiere** [comment]
As far as I can tell, the error is probably on your side: tensorflow expects input dimensions to be specified as integers, not floats.

So your tensor should be of type float32 but the input dimensions should be of type int32.

**Comment by LukasMosser** [comment]
Yes, you are correct. Closing this
