### ISSUE TITLE
perform the semantic segmentation based on Densenet

### ISSUE THREAD

**Issue by huaiyanggongzi** [tdeboissiere/DeepLearningImplementations#15]
Hi Thibault,

Thanks for sharing the Densenet code. If I want to leverage this architecture for semantic segmentation work, do you have any suggestions? My preliminary thought is to add deconvolutional braches, while treating the current densenet as the feature encoding part.  Thanks.

**Comment by tdeboissiere** [comment]
I think it's already been explored in details here: https://arxiv.org/abs/1611.09326
That should be a good starting point.

**Comment by RaananHadar** [comment]
Hi,
I've found a github repository which implemented this very paper quite recently.
You can find it here: [https://github.com/titu1994/Fully-Connected-DenseNets-Semantic-Segmentation](url)
I suggest you check if the code works (I would love to hear your experience with it) and if it does, you can close the issue.
