### ISSUE TITLE
Deconv color meaning

### ISSUE THREAD

**Issue by DanlanChen** [tdeboissiere/DeepLearningImplementations#16]
Hello, I am wondering if the colors (back ground color in each deconv feat map represent some meaning, like which feature map in the original image has more action response in the neuron, like which part of one image does the network reponses most?

**Comment by tdeboissiere** [comment]
The Deconvolution here consists of identifying which image maximally activates a specific neuron and then trying to reconstruct the part of the image that contributed to this activation.

I don't know whether the background color is an artifact or if it has a clear interpretation. In Zeiler's paper, the background is mostly gray...
