### ISSUE TITLE
Notes on "nb_epoch"and "n_batch_per_epoch" is not correct.

### ISSUE THREAD

**Issue by echoaimaomao** [tdeboissiere/DeepLearningImplementations#18]
I am so grateful for you sharing the codes. I am afraid that your notes on "nb_epoch"and "n_batch_per_epoch"  may be just mistaken. It is a small mistake.
The readme file and main.py in ...\WassersteinGAN\src\model\..
readme:
    --nb_epoch NB_EPOCH   Number of batches per epoch
    --batch_size BATCH_SIZE
                          Batch size
    --n_batch_per_epoch N_BATCH_PER_EPOCH
                          Number of training epochs
main.py
    parser.add_argument('--nb_epoch', default=400, type=int, help="Number of batches per epoch")
    parser.add_argument('--batch_size', default=32, type=int, help='Batch size')
    parser.add_argument('--n_batch_per_epoch', default=200, type=int, help="Number of training epochs")

**Comment by tdeboissiere** [comment]
Looks like a typo indeed. Corrected
