### ISSUE TITLE
Error when running InfoGAN with generator as deconv  and increasing bacth size

### ISSUE THREAD

**Issue by mridulbirla** [tdeboissiere/DeepLearningImplementations#19]
Hi,

Firstly thank for sharing your code. I having trouble running the INFOGAN for mnist dataset with generator as deconv and batchsize as 64.  You can find stack trace at https://gist.github.com/mridulbirla/1952e9227253980e1c118120220f8977 .

It looks like it is getting error  in # transposed conv blocks. Do you know how to resolve this error.

**Comment by tdeboissiere** [comment]
Merged, thanks !
