### ISSUE TITLE
A question:

### ISSUE THREAD

**Issue by ChampionZP** [tdeboissiere/DeepLearningImplementations#27]
when i try to run:
         bash make_gif.sh
result is this : 
 **no images defined `MoG_dataset.gif'** 

could you tell me what's wrong, thanks !

**Comment by tdeboissiere** [comment]
Check that you do have images in `list_toy_str`, you most likely have an empty list hence the error.

**Comment by ChampionZP** [comment]
font{
        line-height: 1.5;
    }


    
thank you very much, I fixed it ! thanks!


    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    
    
        font{
            line-height: 1.5;
        }
    
School of  Economics and ManagementUniversity of Chinese Academy of  Sciences

                



    On 03/21/2017 11:45，Thibault de Boissiere<notifications@github.com> wrote： 


Check that you do have images in list_toy_str, you most likely have an empty list hence the error.
