### ISSUE TITLE
Number of epochs for pix2pix

### ISSUE THREAD

**Issue by s4chin** [tdeboissiere/DeepLearningImplementations#28]
Approximately how many epochs did pix2pix take to produce the [example image](https://github.com/tdeboissiere/DeepLearningImplementations/blob/master/pix2pix/figures/img_pix2pix.png)?

Also, are the default settings the ones you used to get the result?

**Comment by tdeboissiere** [comment]
I don't remember exactly but definitely not too long (1 to 2 hours of training).

**Comment by tdeboissiere** [comment]
I don't remember exactly but definitely not too long (1 to 2 hours of training).

**Comment by s4chin** [comment]
For anyone else who wants an answer to this, the result given in the example image occurs at around epoch 200-250 on the default settings.
