### ISSUE TITLE
DeepLearningImplementations/Colorful

### ISSUE THREAD

**Issue by JulienCriss** [tdeboissiere/DeepLearningImplementations#33]
Hello @tdeboissiere ,

For **DeepLearningImplementations/Colorful** how can I make to color a single picture given as input

e.g python main.py eval --img_in my_grayscale_picture.png

Thanks.

**Comment by tdeboissiere** [comment]
Hi Julien,

that should be straightforward to implement through the modification of the plot_batch_eval function in general_utils.py
