### ISSUE TITLE
DeepLearningImplementations/Colorful Error when I try to train on dataset generated by images with dimension greater than 64x64

### ISSUE THREAD

**Issue by JulienCriss** [tdeboissiere/DeepLearningImplementations#36]
Hello @tdeboissiere ,

I can not train with a dataset generated from 68x68 images dimensions or other dimenisions like 128x128. The only dimension that works  it is 64x64,  with other dimensions it gives me this error:

**Traceback (most recent call last):
  File "C:\Anaconda3\envs\py35\lib\site-packages\theano\compile\function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
ValueError: GpuReshape: trying to reshape an array of total size 5769216 into an array of total size 2894624.

During handling of the above exception, another exception occurred:

ValueError: GpuReshape: trying to reshape an array of total size 5769216 into an array of total size 2894624.
Apply node that caused the error: GpuReshape{2}(GpuElemwise{add,no_inplace}.0, TensorConstant{[9248  313]})
Toposort index: 1562
Inputs types: [GpuArrayType<None>(float32, (False, False, False, False)), TensorType(int32, vector)]
Inputs shapes: [(2, 36, 256, 313), (2,)]
Inputs strides: [(11538432, 320512, 1252, 4), (4,)]
Inputs values: ['not shown', array([9248,  313])]
Outputs clients: [[InplaceGpuDimShuffle{0,1,x,x}(GpuReshape{2}.0)]]**

I have as backend Theano and I use the GPU to train.

**Comment by tdeboissiere** [comment]
Hi,

the error message is, as you've noted, a reshape error.
 3 options:

- At some point, you feed inputs of unexpected dimension
- Your image dimensions are not supported (I'd assume it would work for at least 32x32 and 64x64, check the model architecture with keras' graphviz for other image inputs)
- There is a bug somewhere in my code
 
I'm pretty sure you'll find the error in the first 2 points. To solve it, just adapt the convolutions and upsampling/downsampling to your image.
