### ISSUE TITLE
Issue running the code with tensorflow backend

### ISSUE THREAD

**Issue by madhumitabehera** [tdeboissiere/DeepLearningImplementations#37]
I am trying replicate your work on tensorflow as backend.  The Decovnet seems pretty generic code however i am getting error at 
# Tensor for function definitions
 self.x = K.T.tensor4('x')
what exactly can be changed here for tensorflow to make the same code work.

**Comment by tdeboissiere** [comment]
You're looking at creating a tensor of 4 dimensions.
Have a look at tensorflow's documentation to find the theano equivalent
