### ISSUE TITLE
Confusion about your Wasserstein loss function vs one described in paper

### ISSUE THREAD

**Issue by kaijfox** [tdeboissiere/DeepLearningImplementations#39]
The approximate Wasserstein loss you define is:

```python
def wasserstein(y_true, y_pred):
    return K.mean(y_true * y_pred)
```

But in the [paper](https://arxiv.org/pdf/1701.07875.pdf) (Algorithm 1) they optimize:
 ![\frac{1}{m}\sum^{m}_{i=1}f_w(x^{(i)})&space;-&space;\frac{1}{m}\sum^{m}_{i=1}f_w(g_\theta(x^{(i)}))](https://latex.codecogs.com/gif.latex?\frac{1}{m}\sum^{m}_{i=1}f_w(x^{(i)})&space;-&space;\frac{1}{m}\sum^{m}_{i=1}f_w(g_\theta(x^{(i)})))
Where x is the batch of real images, z is the noise input to the generator g, and f is the critic.

Your objective seems to function just fine, since the network clearly learns well. I'm confused where the multiplication is coming from though. Could you explain that part of your code?

**Comment by tdeboissiere** [comment]
That's exactly what I do. In this case, y_true = 1 or -1. So K.mean(y_true * y_pred) is the same as the first part of the equation.

I give more details on the way I optimize this GAN here: https://github.com/tdeboissiere/DeepLearningImplementations/tree/master/WassersteinGAN/src/model
