### ISSUE TITLE
suitable parameter for WGAN on mnist?

### ISSUE THREAD

**Issue by jiangzidong** [tdeboissiere/DeepLearningImplementations#40]
Hi, 
I tried to use the WGAN on mnist, with cmd 
`python main.py --backend=tensorflow --generator deconv --use_mbd`

After several epochs, the G_loss and D_loss are both negative value and very close to zero (e.g. -8.7654*e-7)
And the generated pictures have mode-missing issue.

Do you have a workable parameter for mnist dataset?

My result: first 2 row are generated image.
![current_batch](https://user-images.githubusercontent.com/15059452/27573691-b25772da-5ad8-11e7-83c4-ca5dd18d0400.png)

**Comment by tdeboissiere** [comment]
Not on the top of my head sorry. In theory, the default should work decently well. Try lowering the learning rates to improve results. I generally get better results with upconv architecture instead of deconv.
