### ISSUE TITLE
Exact versions of dependencies for pix2pix net?

### ISSUE THREAD

**Issue by AlexanderFabisch** [tdeboissiere/DeepLearningImplementations#42]
Hi,

I am trying to train the pix2pix model. Unfortunately I get errors with several combinations of Theano / Keras and Tensorflow / Keras. Which versions and which dimension order should I use? Is it documented somewhere?

**Comment by tdeboissiere** [comment]
I have not documented it sorry.
Should run with theano 0.9 or tensorflow 1.0 and keras 1.2.2

**Comment by AlexanderFabisch** [comment]
OK, does not work for me with tensorflow because I use CUDA 8.0 but it seems to work with theano 0.9. At least I did not get an error yet. Should I open a pull request to update the README or can you do that?
