### ISSUE TITLE
Colorful - not compatible with Keras 2

### ISSUE THREAD

**Issue by panuganti** [tdeboissiere/DeepLearningImplementations#45]
I'm trying out Colorful scripts. It looks like the training script does not work with Keras2. Simply downgrading keras to 1.2 etc.. brings new issues. I'd appreciate if the scripts can be upgraded to Keras 2.

**Comment by tdeboissiere** [comment]
You are welcome to try a PR to update the repo. I am unfortunately quite busy at the moment...
