### ISSUE TITLE
Please specify the versions of the python modules in the requirements (Colorful)

### ISSUE THREAD

**Issue by panuganti** [tdeboissiere/DeepLearningImplementations#46]
The code does not run with the latest versions of the packages. Some of them have to be downgraded to earlier versions. Please specify the versions of the python modules that are required to run 'Colorful' scripts

**Comment by tdeboissiere** [comment]
Will do when I get the time. Unfortunately I am quite busy at the moment. You can check some of the closed issues for more information (such issues may have been raised before)

**Comment by tdeboissiere** [comment]
Code has been mostly updated for keras 2. Requirements have been added as well.Closing
