### ISSUE TITLE
InfoGAN doesnt train with default parameters for celebA dataset

### ISSUE THREAD

**Issue by anshkapil** [tdeboissiere/DeepLearningImplementations#56]
After 100 epochs:
D tot: 0.2766 - D log: 0.0055 - D cat: 1.1600 - D cont: -0.8890 - G tot: 11.2585 - G log: 12.5444 - G cat: 0.0936 - G cont: -1.3795

Are there different parameters for celebA dataset ?

**Comment by tdeboissiere** [comment]
I have actually only been able to train successfully with MNIST. CelebA was provided for experimentation but I haven't searched the hyperparam space.
