### ISSUE TITLE
Open PR to add Eve optimizer to keras

### ISSUE THREAD

**Issue by michaelosthege** [tdeboissiere/DeepLearningImplementations#6]
The Readme states that the Eve class can simply be copied to the [keras sources](https://github.com/fchollet/keras/blob/master/keras/optimizers.py). Therefore I'd suggest that @tdeboissiere opens a PR to keras =)

**Comment by tdeboissiere** [comment]
It's probably too early to add the method to keras. From my experiments, it is not clear whether Eve is really better than Adam out of the box.
