### ISSUE TITLE
CelebA dataset is not accessible

### ISSUE THREAD

**Issue by Kernev** [tdeboissiere/DeepLearningImplementations#74]
If you want Align&Cropped images you wil have the following error:
urllib2.HTTPError: HTTP Error 429: Too Many Requests

**Comment by Kernev** [comment]
Here is a Google Drive link:
[https://drive.google.com/drive/folders/0B7EVK8r0v71pWEZsZE9oNnFzTm8](url)

**Comment by Kernev** [comment]
Here is a new link:
[https://drive.google.com/drive/folders/0B7EVK8r0v71pWEZsZE9oNnFzTm8](url)

**Comment by Kernev** [comment]
here is the new link:
[https://drive.google.com/open?id=0B7EVK8r0v71pWEZsZE9oNnFzTm8](url)

**Comment by Kernev** [comment]
Here is a working link:
[https://drive.google.com/open?id=0B7EVK8r0v71pWEZsZE9oNnFzTm8](url)

**Comment by ibarrien** [comment]
@Lambyor: please stop sending messages with links.

**Comment by Kernev** [comment]
Here is a working link
[Google drive link](https://drive.google.com/open?id=0B7EVK8r0v71pWEZsZE9oNnFzTm8)
