### ISSUE TITLE
When I run the source code, should I use TensorFlow as my backend or Theano?

### ISSUE THREAD

**Issue by johnny5550822** [tdeboissiere/DeepLearningImplementations#9]
When I run the source code, should I use TensorFlow as my backend or Theano?

Because it look like it want Theano. I have an error when U try to use tf as backend.

```
Traceback (most recent call last):
  File "/home/kcho/lib/tensorflow/DeepLearningImplementations/DeconvNet/VGG_deconv.py", line 176, in <module>
    Dec = KerasDeconv.DeconvNet(model)
  File "/home/kcho/lib/tensorflow/DeepLearningImplementations/DeconvNet/KerasDeconv.py", line 29, in __init__
    self.x = K.T.tensor4('x')
AttributeError: 'module' object has no attribute 'T'
```

**Comment by tdeboissiere** [comment]
Yes,  theano backend only for the moment.  You are  welcome to try a PR with tensorflow!

**Comment by johnny5550822** [comment]
@tdeboissiere WHat do you mean by PR with tensorflow?

Also, for the DeconvNet/VGG_deconv.py implementation, will there by Tf backend soon?

**Comment by tdeboissiere** [comment]
PR = push request

I was inviting you to have a go at porting the code to the TF backend. I have no plan to do so in the foreseeable future.

**Comment by johnny5550822** [comment]
@tdeboissiere Ah, I see. Ok, if I happen to do so. I will subit a pull request.
